services:
  api:
    build: spotify-clone-back/
    image: frasp/spotify-clone-back:latest
    container_name: api
    environment:
      - frontend.url=http://18.197.108.246
    ports:
      - "8080:8081"
    networks:
      - pd421_spotify-clone
  front:
    build:
      context: spotify-clone-front/
      args:
        - BACKEND_URL=http://18.197.108.246:8080
    image: frasp/spotify-clone-front:latest
    container_name: front
    depends_on:
      - api
    ports:
      - "80:8080"
    networks:
      - pd421_spotify-clone

networks:
  pd421_spotify-clone:
    name: pd421_spotify-clone