spring.application.name=spotify-clone-back
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://ep-polished-firefly-airuithd-pooler.c-4.us-east-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_HNJVAyIEf60v

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.connection.CharSet=UTF-8
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true

user.images.dir=user_images
music.images.dir=music_images
music.dir=music

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs

spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.max-file-size=50MB


my.secret_jwt = "380d3e72e2814015ae3f79d5b61ed79e9987291ba88d4369a1de98c44773feb16e0c3e0d778c411b8f3bd0295a38772d"

server.port=8085

